[2023-09-13T07:38:28.197+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-13T07:38:28.231+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-13T07:38:28.234+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-13T07:38:28.301+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2023-08-24 00:00:00+00:00
[2023-09-13T07:38:28.317+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2023-09-13T07:38:28.379+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'extract_data', 'scheduled__2023-08-24T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp4ury6hr8']
[2023-09-13T07:38:28.392+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask extract_data
[2023-09-13T07:38:28.543+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data.extract_data scheduled__2023-08-24T00:00:00+00:00 [running]> on host 190733975a8f
[2023-09-13T07:38:28.913+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-24T00:00:00+00:00'
[2023-09-13T07:38:29.251+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-09-13T07:38:29.308+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=weather_data, task_id=extract_data, execution_date=20230824T000000, start_date=20230913T073828, end_date=20230913T073829
[2023-09-13T07:38:29.407+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-09-13T07:38:29.426+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-15T11:31:07.928+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-15T11:31:07.962+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-15T11:31:07.963+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-15T11:31:08.011+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2023-08-24 00:00:00+00:00
[2023-09-15T11:31:08.024+0000] {standard_task_runner.py:57} INFO - Started process 329 to run task
[2023-09-15T11:31:08.044+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'extract_data', 'scheduled__2023-08-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpyra_fk43']
[2023-09-15T11:31:08.051+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask extract_data
[2023-09-15T11:31:08.241+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data.extract_data scheduled__2023-08-24T00:00:00+00:00 [running]> on host 4af8904e631c
[2023-09-15T11:31:08.480+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-24T00:00:00+00:00'
[2023-09-15T11:31:08.765+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-09-15T11:31:08.785+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=weather_data, task_id=extract_data, execution_date=20230824T000000, start_date=20230915T113107, end_date=20230915T113108
[2023-09-15T11:31:08.842+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-09-15T11:31:08.868+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
