[2023-09-13T07:38:28.680+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-20T00:00:00+00:00 [queued]>
[2023-09-13T07:38:28.721+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-20T00:00:00+00:00 [queued]>
[2023-09-13T07:38:28.723+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-13T07:38:28.785+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2023-08-20 00:00:00+00:00
[2023-09-13T07:38:28.809+0000] {standard_task_runner.py:57} INFO - Started process 96 to run task
[2023-09-13T07:38:28.828+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'extract_data', 'scheduled__2023-08-20T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmprz5svqgl']
[2023-09-13T07:38:28.833+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask extract_data
[2023-09-13T07:38:29.049+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data.extract_data scheduled__2023-08-20T00:00:00+00:00 [running]> on host 190733975a8f
[2023-09-13T07:38:29.318+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-20T00:00:00+00:00'
[2023-09-13T07:38:29.616+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-09-13T07:38:29.626+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=weather_data, task_id=extract_data, execution_date=20230820T000000, start_date=20230913T073828, end_date=20230913T073829
[2023-09-13T07:38:29.686+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-09-13T07:38:29.704+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-15T11:31:07.951+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-20T00:00:00+00:00 [queued]>
[2023-09-15T11:31:07.971+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.extract_data scheduled__2023-08-20T00:00:00+00:00 [queued]>
[2023-09-15T11:31:07.975+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-15T11:31:08.048+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2023-08-20 00:00:00+00:00
[2023-09-15T11:31:08.064+0000] {standard_task_runner.py:57} INFO - Started process 330 to run task
[2023-09-15T11:31:08.090+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'extract_data', 'scheduled__2023-08-20T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp3epj9l6o']
[2023-09-15T11:31:08.103+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask extract_data
[2023-09-15T11:31:08.311+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data.extract_data scheduled__2023-08-20T00:00:00+00:00 [running]> on host 4af8904e631c
[2023-09-15T11:31:08.520+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-20T00:00:00+00:00'
[2023-09-15T11:31:08.829+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-09-15T11:31:08.842+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=weather_data, task_id=extract_data, execution_date=20230820T000000, start_date=20230915T113107, end_date=20230915T113108
[2023-09-15T11:31:08.874+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-09-15T11:31:08.894+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
